name: test ci

on:
  pull_request:

jobs:
  node-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ['ubuntu-latest']
        node: [20.x]

    steps:
      - name: setup nodeJs ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: checkout
        uses: actions/checkout@v3

      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: yarn install
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: test format
        run: yarn format

      - name: test lint
        run: yarn lint:js

      - name: test css
        run: yarn lint:css

      - name: test typescript
        run: yarn ts:test

      - name: test unit
        run: yarn test
